[package]
name = "iroha2_explorer_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-server = "2.1.1"
derive_more = "0.99"
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
tracing-log = "0.1.2"
tracing-bunyan-formatter = "0.3.2"
tracing-actix-web = "0.5.1"
structopt = "0.3.26"
iroha_client     = { git = "https://github.com/hyperledger/iroha.git", rev = "8d83a3eff33f29b49004a0a5efe643b10f0f256e" }
iroha_data_model = { git = "https://github.com/hyperledger/iroha.git", rev = "8d83a3eff33f29b49004a0a5efe643b10f0f256e" }
color-eyre = "0.5"
serde = "1.0"
serde_json = "1.0"

[profile.dev.package.backtrace]
# to optimize color-eyre
opt-level = 3
