[package]
name = "iroha2_explorer_web"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "tools/genesis-gen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-server = "2.1.1"
awc = "3.0.0"
derive_more = "0.99"
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
tracing-log = "0.1.2"
tracing-actix-web = "0.5.1"
clap = { version = "3.1.12", features = ["derive", "env"] }
iroha_client        = { git = "https://github.com/hyperledger/iroha.git", rev = "fe33f0f2817d0b46f66ff02354c823b25991247f" }
iroha_data_model    = { git = "https://github.com/hyperledger/iroha.git", rev = "fe33f0f2817d0b46f66ff02354c823b25991247f" }
iroha_crypto        = { git = "https://github.com/hyperledger/iroha.git", rev = "fe33f0f2817d0b46f66ff02354c823b25991247f" }
iroha_telemetry     = { git = "https://github.com/hyperledger/iroha.git", rev = "fe33f0f2817d0b46f66ff02354c823b25991247f" }
iroha_core          = { git = "https://github.com/hyperledger/iroha.git", rev = "fe33f0f2817d0b46f66ff02354c823b25991247f" }
color-eyre = "0.5"
serde = "1.0"
serde_json = "1.0"
futures = "0.3.21"
http = "0.2.6"
chrono = { version = "0.4.19", features = ["serde"] }
hex = "0.4.3"
parity-scale-codec = "2.3.1"
rand = { version = "0.8.5", optional = true }
faker_rand = { version = "0.1", optional = true }

[features]
default = ["dev_actor"]
# Enables an actor that fills Iroha with different data. For dev purposes
dev_actor = ["dep:rand", "dep:faker_rand"]

[profile.dev.package.backtrace]
# to optimize color-eyre
opt-level = 3
