[package]
name = "genesis-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive", "env"] }
iroha_client        = { git = "https://github.com/hyperledger/iroha.git", rev = "6e3522c481501f10613093c9f3219d495b67a0e7" }
iroha_data_model    = { git = "https://github.com/hyperledger/iroha.git", rev = "6e3522c481501f10613093c9f3219d495b67a0e7" }
iroha_crypto        = { git = "https://github.com/hyperledger/iroha.git", rev = "6e3522c481501f10613093c9f3219d495b67a0e7" }
iroha_telemetry     = { git = "https://github.com/hyperledger/iroha.git", rev = "6e3522c481501f10613093c9f3219d495b67a0e7" }
iroha_core          = { git = "https://github.com/hyperledger/iroha.git", rev = "6e3522c481501f10613093c9f3219d495b67a0e7" }
color-eyre = "0.5"
serde = "1.0"
serde_json = "1.0"
rand = "0.8.5"
faker_rand = "0.1"

